### ISSUE TITLE
[Simular prestamo] Comportamiento del botón "ingresar"

### ISSUE THREAD

**Issue by Kathy-Damires** [GlobantUy/STB-Bank#10]
Pasos para la ejecución | Resultado Esperado
------------ | -------------
1: Acceder a la Web de STB Simulador de Préstamos |
2: Completar todos los datos obligatorios con datos válidos |
3: Hacer "click" en el botón ingresar |  Redirección al formulario de ingreso

=======================================================

**US asociada :**
#8

**Comment by jonathan-cembranos** [comment]
issue ok.
