### ISSUE TITLE
[Registro] Validar que, accediendo desde el popup de solicitud, en la pantalla de Login se encuentre el botón "Registrarse" y que el mismo redirija a la página de Registro

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#102]
**Precondiciones:**
Tener acceso a la Web de solicitud de préstamo

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamo con usuario deslogueado| 
2: Completar el formulario de préstamo con datos válidos y cliquear el botón "Simular préstamo"|  
3: Desde la pantalla "Resultado del préstamo", cliquear el botón "Simular préstamo"| Se despliega popup indicando que es necesario ingresar como usuario para solicitar el préstamo, con botones "Cancelar" e "ingresar"
4: Cliquear el botón "Ingresar"| El usuario es redirigido a la pantalla de Login
5: Cliquear el botón "Registrarse"| El usuario es redirigido a la página de Registro. La misma contiene los siguientes datos: 
- Título: 'Registro de usuario STB Bank'
- 'Nombres*' de tipo textbox
- 'Apellidos*' de tipo textbox
- 'Fecha de nacimiento*' de tipo Calendar
- 'Email*' de tipo textbox
- 'Contraseña*' de tipo textbox
- 'Confirmación de la contraseña*' de tipo textbox
- 'Departamento*' de tipo dropdown (popular con lista de departamentos del UY)
- 'Género*' de tipo radiobutton, valores, 'Femenino, Masculino, Otro'
- 'Preferencias*' de tipo checkbox con los valores que están en en wireframe
- El botón "Registrarse" se visualiza deshabiltado por defecto.

6: Validación de UI| Validar que la UI se corresponda con el wireframe: 
![image](https://user-images.githubusercontent.com/73362258/104536365-bf04a300-55f6-11eb-86b7-9a4af61e3190.png)

=======================================================

**US asociada:**
#72

**Comment by jonathan-cembranos** [comment]
issue ok.
[video](https://drive.google.com/file/d/1ZenlAeircFmSYakPrFZ28nti1dpqbz-f/view?usp=sharing)
