### ISSUE TITLE
[Log out/tablaADM] El botón log out mal ubicado

### ISSUE THREAD

**Issue by Agustin-Ramirez** [GlobantUy/STB-Bank#106]
**Reproducción**
Pasos para reproducir el bug:
1. Loguearse como administrador
2. Tratar de desloguearse 
4. Ver el error

**Resultado Esperado**
El botón log out se encuentre en su posición correcta.

**Resultado Obtenido**
El botón no se encuentra en su sitio.

**Datos del dispositivo:**
 - Sistema operativo: Windows
 - Browser chrome

**Comment by jonathan-cembranos** [comment]
issue ok.
Testeado desde la rama “fix-logout-admin”.
