### ISSUE TITLE
[Radio button/Simulador] Los Radio button no coinciden con las especificaciones del figma

### ISSUE THREAD

**Issue by Agustin-Ramirez** [GlobantUy/STB-Bank#107]
**Reproducción**
Pasos para reproducir el bug:
1. Ingresar al simulador 
4. Ver el error

**Resultado Esperado**
Los Radio button deberían ser idénticos a los del figma.

**Resultado Obtenido**
Radio button su formato no es el indicado.

**Capturas**
![Captura](https://user-images.githubusercontent.com/72826258/105069183-5e46f180-5a60-11eb-88bf-c038dc678bc2.PNG)

**Datos del dispositivo:**
 - Sistema operativo:  Windows
 - Browser chrome

**Comment by NachoGlobant** [comment]
@Agustin-Ramirez te asigné el bug para que valides el fix y si está Ok lo cierres.
Gracias!

**Comment by Agustin-Ramirez** [comment]
Vuelve a to do porque no esta fixeado correctamente
