### ISSUE TITLE
Creación de forma de cerrar las Modals - Página Resultado de Préstamo

### ISSUE THREAD

**Issue by alejandroGonGon** [GlobantUy/STB-Bank#108]
**Meta**: Como usuario de STB Simulador de préstamos quiero que una forma de cerrar un Modal independientemente de si tiene un botón de ''Cancelar'' o ''Cerrar''.

**Alcance**: El alcance de la historia comprende la redirección a la página de 'Descuento' y los elementos de UI de la misma, los Modals.

**Escenario** 1 - **Selección botón 'Solicitar Préstamo'**
Dado un usuario SI/NO logueado en el sitio de STB Bank el cual se encuentra en la pantalla de 'Descuento'
Cuando el usuario selecciona el botón de 'Solicitar Préstamo'
Entonces se mostrará un Modal de forma de Pop up.

**Escenario** 2 - **Visualizar el cerrado de los Modals** 
Dado un usuario SI/NO logueado en el sitio de STB Bank el cual se encuentra en la pantalla de 'Descuento'
Cuando el usuario selecciona el botón de 'Registrarse'
Entonces el usuario verá una Modal donde tendrá la opcion de cerrar el modal arriba a la derecha de este, con forma de una cruz.

Diseño :
**Usuario Logueado :**
![image](https://user-images.githubusercontent.com/56725406/105081356-d5848180-5a70-11eb-8ade-0d7945c67650.png)
**Usuario Deslogueado :**
![image](https://user-images.githubusercontent.com/56725406/105081655-390eaf00-5a71-11eb-9f29-2408865846c8.png)

**Comment by evadathaguyGlobant** [comment]
Agregar casos de prueba

**Comment by jonathan-cembranos** [comment]
Issue ok.
