### ISSUE TITLE
Agregado del Botón ''Cancelar'' en el Modal : '' Ya tienes un préstamo pendiente''.

### ISSUE THREAD

**Issue by alejandroGonGon** [GlobantUy/STB-Bank#109]
Meta: Como usuario de STB Simulador de préstamos quiero un botón que cierra el modal transferido.

**Alcance**: El alcance de la historia comprende la redirección a la página de 'Descuento' y los elementos de UI de la misma, los Modals seleccionados y la redirección de estos.

**Escenario** 1 - **Selección botón 'Solicitar Préstamo'**
Dado un usuario SI logueado en el sitio de STB Bank el cual se encuentra en la pantalla de 'Resultado de Préstamo'
Cuando el usuario selecciona el botón de 'Solicitar Préstamo'
Entonces se mostrará un Modal de forma de Pop up.

**Escenario** 2 - **Visualizar del Modal : '' Confirmar Préstamo''**
Dado un usuario SI logueado en el sitio de STB Bank el cual se encuentra en la pantalla de 'Resultado de Préstamo'
Cuando el usuario selecciona el botón de 'Solicitar Préstamo'
Entonces el usuario verá una Modal donde se seleccionara el botón que dice : ' Solicitar' y será transferido a otro Modal

**Escenario** 3 - **Visualizar del Modal : '' Ya tienes un préstamo pendiente''**
Dado un usuario SI logueado en el sitio de STB Bank el cual se encuentra en la pantalla de 'Resultado de Préstamo'
Cuando el usuario selecciona el botón de 'Solicitar Préstamo' 
Entonces el usuario selecciona  la opción que dice : ' Solicitar' y será transferido a otro Modal y verá un solo botón que dice : 'Volver al inicio'
Agregar un botón que cierre el Modal ya creado y que diga : 'Cancelar'.

Modal:
![image](https://user-images.githubusercontent.com/56725406/105082231-044f2780-5a72-11eb-9a9d-ad90e66607fc.png)

**Comment by evadathaguyGlobant** [comment]
Agregar casos de prueba

**Comment by NachoGlobant** [comment]
@alejandrogon1418 algunas consultas:
Escenario 1:
- Cuál es el modal que se muestra? Podemos adjuntar una captura?

Escenario 2:
- A qué modal es transferido el usuario? No iría a la pantalla de solicitud?

Escenario 3:
- En la imagen adjunta no se ve el "Cancelar". Se podrá adjuntar captura?

Gracias!
Nacho.-

**Comment by alejandroGonGon** [comment]
> @alejandrogon1418 algunas consultas:
> Escenario 1:
> 
> * Cuál es el modal que se muestra? Podemos adjuntar una captura?
> 
> Escenario 2:
> 
> * A qué modal es transferido el usuario? No iría a la pantalla de solicitud?
> 
> Escenario 3:
> 
> * En la imagen adjunta no se ve el "Cancelar". Se podrá adjuntar captura?
> 
> Gracias!

**Escenario 1**
El modal que se muestra es '' Confirmar Prestamo ''
Captura :
![image](https://user-images.githubusercontent.com/56725406/106632956-0f6b8280-655d-11eb-8b7b-44be077a6f95.png)

**Escenario 2**
Sería transferido al modal '' Ya tienes un préstamo pendiente ''.  Si el usuario anteriormente realizo un préstamo  no iria a ninguna pantalla sino que se le mostrará el modal mencionado anteriormente.


**Escenario 3**
Captura : 
![image](https://user-images.githubusercontent.com/56725406/106635426-91f54180-655f-11eb-85dc-406f596ff8ff.png)

**Comment by NachoGlobant** [comment]
> > @alejandrogon1418 algunas consultas:
> > Escenario 1:
> > 
> > * Cuál es el modal que se muestra? Podemos adjuntar una captura?
> > 
> > Escenario 2:
> > 
> > * A qué modal es transferido el usuario? No iría a la pantalla de solicitud?
> > 
> > Escenario 3:
> > 
> > * En la imagen adjunta no se ve el "Cancelar". Se podrá adjuntar captura?
> > 
> > Gracias!
> 
> **Escenario 1**
> El modal que se muestra es '' Confirmar Prestamo ''
> Captura :
> ![image](https://user-images.githubusercontent.com/56725406/106632956-0f6b8280-655d-11eb-8b7b-44be077a6f95.png)
> 
> **Escenario 2**
> Sería transferido al modal '' Ya tienes un préstamo pendiente ''. Si el usuario anteriormente realizo un préstamo no iria a ninguna pantalla sino que se le mostrará el modal mencionado anteriormente.
> 
> **Escenario 3**
> Captura :
> ![image](https://user-images.githubusercontent.com/56725406/106635426-91f54180-655f-11eb-85dc-406f596ff8ff.png)

Gracias, Ale!

**Comment by jonathan-cembranos** [comment]
issue ok.
