### ISSUE TITLE
[botón/Simulador de préstamos] El botón “Simular préstamo” siempre está activo (su estilo)

### ISSUE THREAD

**Issue by jonathan-cembranos** [GlobantUy/STB-Bank#111]
**Reproducción**
Pasos para reproducir el bug:
1. Ir a 'Simulador de préstamos'
2. Ver el error

**Resultado Esperado**
Un Simulador de préstamos con el botón “Simular préstamo” diseibel con su estilo correspondiente.

**Resultado Obtenido**
Un Simulador de préstamos con el botón “Simular préstamo” sin su estilo correspondiente.

**Capturas**
![bug4](https://user-images.githubusercontent.com/72940883/105227383-fb2c8c00-5b3f-11eb-9165-7886c3318f4e.PNG)

**Datos del dispositivo:**
 - Sistema operativo: Windows
 - Browser: chrome

**Comment by Kathy-Damires** [comment]
#16
