### ISSUE TITLE
Guardar en la BD información de usuario que se registra y permitir logueo

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#112]
**Meta:** Como usuario que completa el formulario de registro y presiona 'Registrarse' quiero que mi información se guarde correctamente en la BD y que se me asigne el tipo de usuario regular, luego debo poder ingresar sin problemas al sito utilizando las credenciales registradas

**Alcance:** guardar la info del usuario en la BD, asignarle el tipo 'regular' y permitirle el ingreso al sistema

**Escenario 1 - Registro de usuario**
**Dado** un usuario que completa el formulario de registro
**Cuando** el usuario ingresa sus datos y selecciona el botón 'Registrarse'
**Entonces** su información se guarda en la base de datos y se le asigna el tipo de usuario regular

**Escenario 2 - Login usuario que se acaba de registrar**
**Dado** un usuario que ha completado el formulario de registro y ha presionado 'Registrarse'
**Cuando** el usuario completa sus credenciales en el login
**Entonces** el usuario puede acceder correctamente y al ser un usuario de tipo regular es automáticamente redirigido a la página de solicitud de préstamos

**Diseño:**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by RominaGlobant** [comment]
@evadathaguyGlobant Cómo estás?
Te dejo por aquí una duda:

1. Cuando el usuario completa el formulario de registro y hace click en 'Registrarse' qué pasa después? (Por ejemplo, visualiza algún tipo de mensaje 'Gracias por su registro',  es redirigido mientras tanto a otra página? etc?)

Muchas gracias!

**Comment by alejandroGonGon** [comment]
> @evadathaguyGlobant Cómo estás?
> Te dejo por aquí una duda:
> 
> 1. Cuando el usuario completa el formulario de registro y hace click en 'Registrarse' qué pasa después? (Por ejemplo, visualiza algún tipo de mensaje 'Gracias por su registro',  es redirigido mientras tanto a otra página? etc?)
> 
> Muchas gracias!

Tras registrarse, el usuario en redirigido al '' Home  ''(Simular prestamo) si es un customer o a la '' Tabla Admin '' si es un Admin. En ningún momento salta un cartel o mensaje avisando que se registro, tengo entendido que no se tomó en cuenta.

**Comment by jonathan-cembranos** [comment]
issue ok.
