### ISSUE TITLE
No permitir registro de usuario con un mail ya existente

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#114]
**Meta:** Como administrador de STB Bank no quiero permitir que haya más de un usuario registrado con el mismo correo electrónico y mostrar un pop-up

**Alcance:** creación del pop-up 

**Escenario 1 - Pop up**
**Dado** un usuario que completa el formulario de registro y ha ingresado un correo electrónico ya existente en la BD
**Cuando** el usuario  selecciona el botón 'Registrarse'
**Entonces** se muestra un pop up
y el título es 'Usuario no se ha registrado'
y el texto es 'Ya existe un usuario con el Email ingresado, pruebe con otro.'
y hay un botón de 'OK' 
y el usuario no se guarda en la BD

**Escenario 2 - Selección de 'OK'**
**Dado** un usuario que está en el pop up de registro erróneo
**Cuando** el usuario  selecciona el botón 'OK'
**Entonces** se cierra el pop up y se pone el cursor en el campo de email

**Diseño:**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
Se despliega un mensaje de error, pero este no muestra el contenido deseado.

**Comment by jonathan-cembranos** [comment]
issue ok.
