### ISSUE TITLE
Aprobar y rechazar préstamos pendientes y aplicar cambios

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#115]
**Meta:** Como usuario admin que se loguea en el sitio quiero poder visualizar información de los préstamos en la página de visualización de préstamos y aprobar o rechazar los mismos

**Alcance:** aplicar un rechazo o aprobación

**Dado** un usuario admin 
**Cuando** el usuario cambia el estado de un préstamo pendiente a 'Aprobado' o 'Rechazado' y selecciona 'Aplicar cambios'
**Entonces** las lineas que fueron cambiadas ahora se muestran con el fondo en blanco
y se actualiza el estado en la base de datos
y se muestra correctamente el estado en la UI
y el estado es final (ya no aparece el dropdown con las opciones)

**Diseño:**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
Este issue no está terminado debido a varios errores.
[Video de los errores](https://drive.google.com/file/d/1O3EvQsNC6-HRRzlWk1Qc28nXDflj6tyz/view?usp=sharing)
(se recomienda adelantar o aumentar la belosidad de reproduccion del mismo)

**Comment by jonathan-cembranos** [comment]
issue ok
