### ISSUE TITLE
(Backend/Modificar el estado de un prestamo) Modificar el endpoint para poder cambiar el estado de varios prestamos con una sola request

### ISSUE THREAD

**Issue by Kevin-Mora-Pais** [GlobantUy/STB-Bank#116]
Actualmente la página permite modificar el estado de varios prestamos en simultaneo al hacer click en "Aplicar cambios", pero el backend solo puede modificar un estado por request.

Endpoint: https://backendmain-gktbdrcfz.vercel.app/api/updateLoan

Formato de request (ejemplo): 
{
 "data": [ {"email": "kathy@test.com", "state": true}, {"email": "devTest2@test.com", "state": false}]
  
}

**Comment by RominaGlobant** [comment]
@Kevin-Mora-Pais  Cómo estás?
Te dejo aquí algunas consultas respecto a tu endpoint:

1. Si lo que queremos es aplicar cambios en los estados de los prestamos: Aprobado/Rechazado/Pendiente - Podrías mostrarnos un ejemplo más concreto de cómo deben de pasar la request?
2. Qué tipo de request es? POST?
3. Qué resultado eperamos que nos devuelva la request una vez ejecutada? (Ejemplo: algún mensaje en particular en el backend?
4. Qué status code retornará la request?
5. Además de poder controlar si los estados de los prestamos se actualizaron correctamente mediante la UI - podrías proporcionar una QUERY a la BD que refleje los cambios?

Muchas gracias por tu tiempo!

**Comment by Kevin-Mora-Pais** [comment]
Hola Romi. Bien,  vos? 

1. Los unicos valores que el endpoint puede recibir como estado son Aprobado (true) y Rechazado (false). El estado Pendiente (undefined) es el valor que se le asigna a un prestamo por default al momento de que un usuario lo solicita.

Respecto al formato, se debe de enviar un array llamado "data" con el correo de cada usuario y el estado a aplicar dentro de un objeto. 

Por ejemplo: 
{
 "data": [ {"email": "email2@test.com", "state": true}, {"email": "email2@test.com", "state": false}]
}

2. El metodo es POST.

No te puedo responder las demas preguntas ahora ya que va a haber algunos cambios en el endpoint. Apenas esté todo implementado te respondo en esta misma issue.
