### ISSUE TITLE
Incorporar tooltips a mensajes de error inline

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#118]
![image](https://user-images.githubusercontent.com/72990925/105889857-66b5a400-5fed-11eb-8200-bc8f48c2e4f5.png)

**Comment by RominaGlobant** [comment]
Hola @Kathy-Damires  y @bruno-dossantos  cómo están?
Les dejo aquí algunas consultas:

1. Para qué mensajes de error online incorporaron tooltips, algunos o todos?
2. Podrían detallar cuáles son los mensajes de error y la tooltip correspondiente?
3. Podrían adjuntar captura de pantalla de cómo se tendrían que ver al menos 1 o 2 tooltip según el error?

Muchas gracias por su tiempo!

**Comment by bruno-dossantos** [comment]
Hola @RominaGlobant todo bien?

Las tooltips se incorporaron en todos los campos obligatorios. Hay 2 tipos de mensajes: el primero es una tooltip con el mensaje "Este campo es obligatorio" que se aplicará en todos los campos que son requeridos, y despues estan los errores por debajo del input que el mensaje de error va a depender del input.

Te adjunto captura de los 2 tipos de mensajes:
![Mensaje tipo 1](https://user-images.githubusercontent.com/72825324/107401429-a39b9380-6ae1-11eb-92e2-b2a2ac83f467.png)
![Mensaje tipo 2](https://user-images.githubusercontent.com/72825324/107401432-a4342a00-6ae1-11eb-9db1-d60a7dbbf7ca.png)

Culaquier cosa no dudes en volver a consultar, saludos!
