### ISSUE TITLE
[UI/Visualización de préstamos] Falta implementar 2 estilos, el font-family del texto “No hay datos ingresados aún” y el filtro por estado.

### ISSUE THREAD

**Issue by jonathan-cembranos** [GlobantUy/STB-Bank#125]
**Precondiciones**
Tener acceso a un usuario con el rol de administrador y que no exista ningún préstamo (ningún préstamo en absoluto independientemente de su estado).

**Reproducción**
Pasos para reproducir el bug:
1. Ir a 'Ingresar'
2. Ingresar con un usuario con el rol de administrador
3. Ver el error

**Resultado Esperado**
Una página de “Visualización de préstamos” cuyos estilos son iguales al figma.

**Resultado Obtenido**
Una página de “Visualización de préstamos” cuyos estilos no son iguales al figma.

**Capturas**
![bug 5](https://user-images.githubusercontent.com/72940883/105897645-3410a900-5ff7-11eb-99d1-c07ee30144b1.PNG)

**Datos del dispositivo:**
 - Sistema operativo: Windows
 - Browserj: chrome

**Comentario**
Por favor comparar con el figma.

**Comment by NachoGlobant** [comment]
@jonathan-cembranos te asigné el bug para que valides el fix y si está Ok lo cierres.
Gracias!

**Comment by jonathan-cembranos** [comment]
Issue no finalizada.
Los errores en los estilos aún no están resueltos.

**Comment by jonathan-cembranos** [comment]
issue ok.
