### ISSUE TITLE
[Botón simular prestamo/Simular prestamo] Según la issue #8 el boton debe permanecer disable mientras los campos no esten llenos, pero permanece habilitado en todo momento

### ISSUE THREAD

**Issue by Kathy-Damires** [GlobantUy/STB-Bank#126]
**Reproducción**
Pasos para reproducir el bug:
1. Ir a 'Simular prestamos/home'
2. Cliquear 'No llenar ningun campo'
3. Ver el error

**Resultado Esperado**
Al no llenar ningun campo el boton no debería esta habilitado.

**Resultado Obtenido**
El boton permanece habilitado en todo momento.

**Capturas**
![image](https://user-images.githubusercontent.com/56728912/106039110-7bf70500-60b7-11eb-9bfa-86ee728f40df.png)

US
#8
Test case
#16

**Comment by jonathan-cembranos** [comment]
issue duplicado
