### ISSUE TITLE
[Visualización de préstamos] Visualización de pantalla "Solicitudes" con usuario Admin

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#127]
**Precondiciones:**
Se debe contar con un usuario Admin
El usuario debe tener varios préstamos ingresados, con estado finalizado (Aprobado, Rechazado) y no finalizado (Pendiente) 

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamos con usuario Admin| 
2: Visualizar la página "Solicitudes"| Validar que todos los campos se visualizan correctamente: El campo 'Filtro por estado' es un combo y por defecto se visualiza vacío; en la primera columna, todos los checkbox se encuentran descliqueados por defecto; en la columna "Usuario" se ve el nombre del usuario; en la columna "Monto solicitado" el monto del préstamo; en la columna "Fecha" la fecha en formato correcto según Figma; en la columna "Moneda" la moneda del préstamo; en la columna "Cuotas" la cantidad de cuotas solicitada, y en la columna "Estado" el estado del préstamo. Si el préstamo está pendiente, se visualiza un chevrón que despliega un listado para aprobar y rechazar el préstamo; si el préstamo está rechazado o aprobado, no se visualiza el chevrón; Además se visualiza el botón "Aplicar cambios" deshabilitado | 

=======================================================

**US asociada:**
#46

**Comment by jonathan-cembranos** [comment]
issue ok.
