### ISSUE TITLE
[Botón Cancelar] Cuando se muestra el modal de confirmación de préstamo y se cliquea 'Cancelar' se cancela la solicitud

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#132]
**Precondiciones:**
Se debe contar con un usuario válido para solicitar un préstamo

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamos| 
2: En el formulario, ingresar datos válidos| 
3: Cliquear 'Simular préstamo'| 
4: En la pantalla "Resultado del préstamo, cliquear 'Solicitar préstamo'| Se despliega un popup con las opciones 'Cancelar' y 'Solicitar' 
5: Cliquear 'Cancelar'| El usuario permanece en la pantalla 'Resultado del préstamo'

![image](https://user-images.githubusercontent.com/73362258/107305691-31d03500-6a62-11eb-9c4a-5a6377e25e45.png)

=======================================================

**US asociada:**
#109

**Comment by jonathan-cembranos** [comment]
issue ok.
