### ISSUE TITLE
[Botón Solicitar] Cuando se muestra el modal de confirmación de préstamo y se cliquea 'Solicitar' se envía la solicitud correctamente

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#133]
**Precondiciones:**
Se debe contar con un usuario válido para solicitar un préstamo

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamos| 
2: En el formulario, ingresar datos válidos| 
3: Cliquear 'Simular préstamo'| 
4: En la pantalla "Resultado del préstamo, cliquear 'Solicitar préstamo'| Se despliega un popup con las opciones 'Cancelar' y 'Solicitar' 
5: Cliquear 'Solicitar'| Se despliega popup indicando que el préstamo se envió correctamente y está en espera de aprobación

![image](https://user-images.githubusercontent.com/73362258/107305627-16fdc080-6a62-11eb-9527-73c349eff6a8.png)

=======================================================

**US asociada:**
#109

**Comment by jonathan-cembranos** [comment]
issue ok.
