### ISSUE TITLE
[Préstamo pendiente] Cuando el usuario tiene un préstamo pendiente de aprobación se despliega popup indicándolo

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#134]
**Precondiciones:**
Se debe contar con un usuario válido para solicitar un préstamo
El usuario debe tener un préstamo pendiente de aprobación

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamos| 
2: En el formulario, ingresar datos válidos| 
3: Cliquear 'Simular préstamo'| 
4: En la pantalla "Resultado del préstamo, cliquear 'Solicitar préstamo'| Se despliega un popup con las opciones 'Cancelar' y 'Solicitar' 
5: Cliquear 'Solicitar'| Se despliega un popup indicando que el usuario tiene un préstamo pendiente
6: Cliquear 'Cancelar'| El usuario permanece en la pantalla "Resultado del préstamo"
7: Cliquear 'Solicitar' nuevamente| 
8: Cliquear 'Volver al inicio'| El usuario es redirigido al inicio 

![image](https://user-images.githubusercontent.com/73362258/107305922-a6a36f00-6a62-11eb-8b80-7eeaaa6fc516.png)

=======================================================

**US asociada:**
#109

**Comment by jonathan-cembranos** [comment]
issue ok.
