### ISSUE TITLE
[Registro con mail ya existente] Cuando el usuario quiere registrarse con un correo ya existente se despliega popup de error

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#136]
**Precondiciones:**
Se debe contar con un correo ya existente en la base de datos

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamos| 
2: Acceder al formulario de registro| 
3: Ingresar todos los datos válidos, el correo ingresado ya debe existir como usuario en la BD| 
4: Cliquear el botón 'Registrarse'| Se muestra un popup con título 'Usuario no se ha registrado' y texto es 'Ya existe un usuario con el Email ingresado, pruebe con otro.'
5: Cliquear el botón 'OK' | El usuario vuelve al formulario de registro con el cursor en el campo 'email', no se crea el usuario y no se guarda en la BD

=======================================================

**US asociada:**
#114

**Comment by jonathan-cembranos** [comment]
Se despliega un mensaje de error, pero este no muestra el contenido deseado.

**Comment by jonathan-cembranos** [comment]
issue ok.
