### ISSUE TITLE
[Aprobar préstamo pendiente] Cuando se aprueba un préstamo el mismo se envía correctamente

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#137]
**Precondiciones:**
Se debe contar con un usuario administrador
El usuario debe tener al menos un préstamo pendiente

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamos con un usuario administrador| 
2: En la pantalla 'Solicitudes' cliquear un préstamo pendiente| 
3: Modificar el mismo a 'Aprobado'| 
4: Cliquear 'Aplicar cambios'| La línea modificada ahora se muestra con el fondo en blanco, se actualiza el estado en la base de datos y se muestra correctamente el estado en la UI. Además, ya no se visualiza el dropdown en la opción de esa línea (estado final)

=======================================================

**US asociada:**
#115

**Comment by jonathan-cembranos** [comment]
issue ok.
