### ISSUE TITLE
[Simular Prestamo] Comportamiento del dropdown "Años de financiación"

### ISSUE THREAD

**Issue by alejandroGonGon** [GlobantUy/STB-Bank#14]
Pasos para la ejecución | Resultado Esperado
------------ | -------------
1: Acceder a la Web de STB Simulador de Préstamos | 
2: Validar los valores del dropdown "Años de financiación" | Los valores :  5, 10, 15, 20 y 25 estan fijos.

=======================================================

**US asociada:**
_https://github.com/GlobantUy/STB-Bank/issues/8_

**Comment by Kathy-Damires** [comment]
los valores son 5, 10, 15, 20 y 25, y son diferentes a los valores especificados en este testcase
