### ISSUE TITLE
[Aprobar y rechazar préstamos pendientes] Cuando se aprueban y rechazan préstamos pendientes los mismos se envían correctamente

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#141]
**Precondiciones:**
Se debe contar con un usuario administrador
El usuario debe tener varios préstamos pendientes

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder al simulador de préstamos con un usuario administrador| 
2: En la pantalla 'Solicitudes' cliquear varios préstamos pendientes| 
3: Modificar algunos a 'Aprobado' y algunos a 'Rechazado'| 
4: Cliquear 'Aplicar cambios'| Las lineas que fueron cambiadas ahora se muestran con el fondo en blanco, se actualizan los estados en la base de datos y se muestran correctamente los estados en la UI. Además, ya no se visualiza el dropdown en las opciones de esas líneas (estado final)

=======================================================

**US asociada:**
#115

**Comment by jonathan-cembranos** [comment]
issue ok.
