### ISSUE TITLE
[Back End - Endpoint Modificar Estado de Préstamo] Modificar el estado de varios préstamos enviando 1 request.

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#143]
Info: Actualmente la página (UI) )permite modificar el estado de varios prestamos en simultaneo al hacer click en "Aplicar cambios", pero el backend solo puede modificar un estado por request.

**Objetivo**
A nivel de backend, debemos de poder enviando una request, modificar el estado de varios préstamos.

Endpoint info:

Request: https://backendmain-gktbdrcfz.vercel.app/api/updateLoan

Formato de request (ejemplo):

{
"data": [ {"email": "kathy@test.com", "state": true}, {"email": "devTest2@test.com", "state": false}]
}

Resultado esperado: {TBD}

=======================================================

**US asociada:**
_[#116 ]_

**Comment by jonathan-cembranos** [comment]
Se comprobó que es posible modificar el estado de varios préstamos al mismo tiempo.
