### ISSUE TITLE
[Registro de Usuario / Login] Registrar un usuario, controlar la DB y loguearse en la App con las credenciales del usuario.

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#144]
**Precondiciones:**
- El usuario visualiza y completa el formulario de registro y presiona 'Registrarse'
- Se debe de tener acceso a la BD para controlar que el usuario quedó registrado y con el tipo de usuario 'regular'
 
=======================================================

**Escenario 1 - Registro de usuario y control en DB**

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Estar el home de STB bank y clickear el botón 'Ingresar' en el margen superior derecho de la App. | Redireccionamiento a la página de 'Login'
2:  Una vez en la pagina de 'Login', clickear el botón 'Registrarse' | Redireccionamiento a la página de 'Registro'
3:  En la página de 'Registro' completar los campos requeridos |
4:  Click en el botón 'Registrarse' | Tras registrarse, el usuario en redirigido al '' Home ''(Simular prestamo) si es un customer o a la '' Tabla Admin '' si es un Admin. 
5:  Una vez registrado el usuario, en paralelo utilizar la Base de Datos para controlar { solicitar una QUERY- a Kevin} que luego de hecho el click en 'Registrarse' los datos ingresados hayan sido guardados en la base. | Todos los datos ingresados para el registro deben de figurar en la base de datos y en tipo de usuario el valor debe de ser: regular.

**Escenario 2 - Login de usuario previamente registrado**

Pre-condición: Se controló en la Base de Datos que el usuario quedó registrado y con el tipo de usuario: 'regular'

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Estar el home de STB bank y clickear el botón 'Ingresar' en el margen superior derecho de la App. | Redireccionamiento a la página de 'Login'
2:  Una vez en la pagina de 'Login', ingresar las credenciales del usuario que se registró previamente en el Escenario 1 | Al ser un usuario del tipo 'regular' luego de haber hecho click en 'Ingresar' se debe de observar un redireccionamiento a la página de 'Solicitudes de Préstamos'

=======================================================

**US asociada:**
_[#112]_

**Comment by jonathan-cembranos** [comment]
Al registrarse se guardan los datos en la base de datos pero el usuario es redireccionado al 

Login en vez de al Home (“Simulador de préstamos”).

Al ingresar con el usuario creado en el escenario 1 (y cualquier otro usuario) el mismo es redirigido al Home. Para que el usuario vea sus préstamos se debe de dirigir a la esquina superior derecha, colocarse sobre el logo de usuario al lado de el username y luego seleccionar la opción “Préstamos”.

¿Debería ser este el flujo recomendado para el usuario aunque no coincida con este Test Case?

**Comment by jonathan-cembranos** [comment]
issue ok.
