### ISSUE TITLE
Visualización de resultado de préstamos

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#30]
**Meta:** Como usuario que accede a la web de STB Simulador de préstamos quiero poder ver las coutas de el préstamo para decidir si quiero solicitarlo

**Alcance:** Creación de los elementos de la pantalla de resultado de préstamo, de momento los mismos no triggerean ninguna acción ni validaciones, lo ultimo será parte de otra historia

**Elementos de la pantalla:**
Título - 'Resultado de préstamo'
'Ingreso' - %Ingresos%
'Monto solicitado'- %MontoSolicitado%
'Seleccione la fila deseada para pedir el préstamo' 
Tabla con campos:
- %Moneda%
- Tasa (fijo, 10,15,18,20,25)
- Cuotas (fijo, 60,120,180,240,300)
- Años(fijo, 5,10,15,20,25)
- Valor cuota (= (%montoSolicitado% *tasa)/cuotas

**Nota:** por defecto ninguna de las lineas de la tabla vienen seleccionadas y el botón 'Solicitar préstamo está deshabilitado'.
Al seleccionar una linea de la tabla el botón se habilita, y toda la linea se marca en naranja claro tal cual las especificaciones del diseño

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
issue ok
