### ISSUE TITLE
Validación de campos Formulario

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#31]
**Meta:** Como usuario que accede a la web de STB Simulador de préstamos quiero tener implementadas ciertas validaciones con respecto a los ingresos vs monto a pedir

**Alcance:** Mostrar una validación inline de error bajo el monto a pedir, salario

**Regla:**
La cuota no puede superar el 20% del sueldo para los años de financiación seleccionados (se debe considerar el interés)
 Ej:
Sueldo: 60.000
Monto a solicitar:  300.000
Años: 5
Interés: 20%
Monto a pagar mensual: 6000
Resultado: OK

**Monto supera en 20% del salario en "n"cuotas**
**Dado** un usuario en la pagina de simulación de préstamo
**Cuando** el usuario ingresa un monto a solicitar que supera el 20% de su sueldo para las cuotas seleccionadas (años, se debe considerar el interés) y selecciona 'Solicitar préstamo'
**Entonces** se muestra una validación inline en rojo (**DONDE????**)
y el texto de la validación es 'El monto a solicitar supera el 20% de su sueldo, por favor intente con un monto menor'
y el usuario no puede proseguir con la solitud hasta modificar el campo

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
La tarea fue finalizada, pero en el momento que sale el mensaje de error el botón queda debajo del footer.

**Comment by Agustin-Ramirez** [comment]
Issue ok
