### ISSUE TITLE
Solicitar préstamo usuario logueado en el sitio

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#32]
**Meta:** Como usuario logueado que accede a la web de STB Simulador de préstamos quiero poder solicitar un préstamo para que el mismo quede pendiente de aprobación

**Escenario 1 - Solicitar préstamo usuario logueado**
**Dado** un usuario en la página de 'Resultado del préstamo' el cual se encuentra logueado en el sitio
**Cuando** el usuario selecciona el botón 'Solicitar préstamo'
**Entonces** se muestra un pop-up de confirmación 
y el título es 'Confirmar préstamo'
y el texto es '¿Desea pedir un prestamo valor %valorPrestamo% en %cantidadCuotas% cuotas?'
y los botones son:
- 'Cancelar'
- 'Solicitar préstamo'

**Escenario 1.1 - Seleccionar botón 'Solicitar préstamo' en pop-up**
**Dado** un usuario en la página de 'Resultado del préstamo' el cual se encuentra logueado en el sitio en el pop-up de confirmación
**Cuando** el usuario selecciona el botón 'Solicitar préstamo'
**Entonces** se muestra un pop-up de confirmación de que el préstamo fue enviado con éxito
y el texto del pop-up es 'Su préstamo se ha registrado exitosamente y se encuentra pendiente de aprobación'
y hay un botón 
y el texto del botón es 'Volver al inicio'

**Escenario 1.1.1 - Seleccionar botón 'Volver al inicio'**
**Dado** un usuario logueado el cual ha solicitado un préstamo y se encuentra en el pop-up de confirmación de solicitud
**Cuando** el usuario selecciona el botón 'Volver al inicio'
**Entonces** el usuario es redirigido al Formulario de préstamos (https://github.com/GlobantUy/STB-Bank/issues/8)
y los campos previamente ingresados están vacíos

**Escenario 1.2 - Seleccionar botón 'Cancelar**
**Dado** un usuario en la página de 'Resultado del préstamo' el cual se encuentra logueado en el sitio en el pop-up de confirmación
**Cuando** el usuario selecciona el botón 'Cancelar'
**Entonces** se cierra el pop-up y el usuario se mantiene en la pagina

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
issue ok.
