### ISSUE TITLE
Volver a simular préstamo

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#33]
**Meta:** Como usuario de 'STB Simulador de préstamos' que simula un préstamo para solicitarlo, si no estoy conforme con el resultado quiero tener la posibilidad de poder volver a simularlo.

**Seleccionar botón 'Volver a simular'**
**Dado** un usuario en la página de 'Resultado del préstamo'
**Cuando** el usuario selecciona el botón 'Volver a simular'
**Entonces** el usuario es redirigido a la página anterior y los campos previamente ingresados se encuentran prepopulados

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
Al llenar únicamente los campos de “Ingreso”, “Monto a pedir” y apretar el botón, el usuario es redirigido a Resultado de préstamo (“Descuento”)  aunque no haya completado las demás áreas.

**Comment by jonathan-cembranos** [comment]
Issues ok.
