### ISSUE TITLE
Solicitar préstamo usuario NO logueado en el sitio

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#34]
**Meta:** Como usuario no logueado que accede a la web de STB Simulador de préstamos quiero poder solicitar un préstamo para que el mismo quede pendiente de aprobación

**Escenario 1 - Solicitar préstamo usuario NO logueado**
**Dado** un usuario en la página de 'Resultado del préstamo' el cual NO se encuentra logueado en el sitio
**Cuando** el usuario selecciona el botón 'Solicitar préstamo'
**Entonces** se le muestra un pop-up
y el título es 'Ingresar'
y el texto es 'Necesita ingresar como usuario para poder solicitar el préstamo'
y hay dos botones:
- 'Ingresar'
- 'Cancelar'

**Escenario 2.1 - No logueado - Seleccionar 'Cancelar'**
**Dado** un usuario en la página de 'Resultado del préstamo' el cual NO se encuentra logueado en el sitio y ha seleccionado la opción 'Solicitar préstamo'
**Cuando** el usuario selecciona el botón 'Cancelar' en el pop-up de 'Ingresar'
**Entonces** se cierra el pop y el usuario queda en la misma página

**Escenario 2.2 - No logueado - Seleccionar 'Ingresar'**
**Dado** un usuario en la página de 'Resultado del préstamo' el cual NO se encuentra logueado en el sitio
**Cuando** el usuario selecciona el botón 'Ingresar'
**Entonces** el usuario es redirigido al login (https://github.com/GlobantUy/STB-Bank/issues/5)

**Escenario 2.2.1 - No logueado - Se loguea**
**Dado** un usuario que viene del caso anterior
**Cuando** el usuario  se autentica correctamente
**Entonces** el usuario es redirigido al login (https://github.com/GlobantUy/STB-Bank/issues/5)
y luego de autenticado correctamente es redirigido al escenario 1 de la historia https://github.com/GlobantUy/STB-Bank/issues/32

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
issue ok.
