### ISSUE TITLE
[Simulador] Comportamiento del campo "Ingreso"

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#36]
Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Acceder a la Web de STB Simulador de Préstamos| 
2: En el campo "Ingreso" ingresar caracteres no numéricos distintos de "+,-,e"| No se permite agregar caracteres no numéricos
3: En el campo "Ingreso" ingresar caracteres numéricos | Se permite ingresar caracteres numéricos
4: En el campo "Ingreso" ingresar los caracteres "+,-,e"| Se permite ingresar los caracteres mencionados
5: En el campo "Ingreso" ingresar los caracteres "+,-,e" y caracteres numéricos| Se permite el ingreso de todos los caracteres

=======================================================

**US asociada:**
#8

**Comment by jonathan-cembranos** [comment]
issue ok.
