### ISSUE TITLE
Usuario Logueado en STB Simulador de préstamos

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#42]
**Meta:** Como usuario que accede a la web de STB Simulador de préstamos quiero poder ver arriba a la derecha mi información de usuario en caso de estar autenticado en el sitio y no perder mi información mientras navego en el sitio.

**Escenario 1 - Usuario logueado**
**Dado** un usuario que se encuentra autenticado en el sitio (ya sea usuario admin o usuario regular)
**Cuando** navega por cualquiera de las páginas del sitio
**Entonces** a la derecha arriba verá su nombre y apellido (tenemos estos datos en la tabla? sino lo que sea que haya puesto en el email antes del @)

**Escenario 2 - Usuario no logueado**
**Dado** un usuario que NO se encuentra autenticado en el sitio
**Cuando** navega por cualquiera de las páginas del sitio
**Entonces** a la derecha arriba verá un botón de 'Ingresar' para autenticarse en el sitio

**Diseño:**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
issue ok.
