### ISSUE TITLE
Usuario Logueado - Deslogueo

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#43]
**Meta:** Como usuario logueado en web de STB Simulador de préstamos quiero poder desloguearme del sitio

**Escenario 1 - Mostrar opción 'Salir'**
**Dado** un usuario logueado en el sitio en cualquiera de las páginas
**Cuando** el usuario selecciona su nombre a la derecha arriba
**Entonces** se despliega la opción 'Salir'
y si el usuario selecciona fuera de la sección entonces la sección se cierra (y el usuario sigue logueado)

**Escenario 2 - Seleccionar opción 'Salir'**
**Dado** un usuario logueado en el sitio en cualquiera de las páginas
**Cuando** el usuario selecciona su nombre a la derecha arriba y la opción 'Salir'
**Entonces** el usuario es redirigido a la página con el formulario de solicitud de préstamos (y el mismo se encuentra vacío)

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
Issue no terminada, tiene un bug (issue #85)
