### ISSUE TITLE
Revisar IU con team de Diseño

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#44]
**Meta:** Revisar con el equipo de diseño (Ana y Vero) las páginas construidas hasta ahora de manera de detectar y corregir inconsistencias, dejar documentado en los comentarios

**Comment by bruno-dossantos** [comment]
Logo con redireccion a home.
Arreglar linea del header (que esté al 100% en ancho).
Modificar titulos en general.
Modificar el alto de los input a un 32px.
Checkbox en color naranja en Simulador de prestamos.
Alineacion de ckeckbox en Simulador de prestamos.
Correjir alto en botones (en general).
Ajustar padding entre label e input (basandose en figma)
En _Resultado de prestamo_ modifcar fuente en general.
