### ISSUE TITLE
Popular con data la página de visualización de préstamos

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#46]
**Meta:** Como usuario admin que se loguea en el sitio quiero poder visualizar información de los préstamos en la página de visualización de préstamos

**Alcance:** popular la información de los préstamos solicitados en la tabla

**Dado** un usuario admin 
**Cuando** el usuario ingresa sus datos y selecciona el botón 'Ingresar'
**Entonces** es redirigido a la página de visualización de préstamos
y puede visualizar correctamente los préstamos ingresados por la web en la tabla
y todos los campos mostrados son correctos

**Diseño:**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
1 El contenido del título no concuerda con lo especificado en figma. 
2 El título y el texto “Filtro por estado” son h2.  
3 Por alguna razón no se está aplicando el estilo de “font-family: 'Roboto' sans-serif” al título.
4 El estilo de “Filtro por estado” debería ser “Roboto” no “Heebo” según Figma.

**Comment by jonathan-cembranos** [comment]
issue ok.
