### ISSUE TITLE
Visualización de préstamos solicitados cuando no hay préstamos

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#48]
**Meta:** Como usuario admin en la página de visualización de solicitud de préstamos cuando no hay préstamos para visualizar quiero poder ver un mensaje que me indique la situación

**No hay préstamos para visualizar** 
**Dado** un usuario admin en la página de visualización de préstamos
**Cuando** no hay préstamos para listar en la tabla
**Entonces** el dropdown de filtros se encuentra vacío
el botón de aplicar cambios no está en la página
y hay una imágen y el texto 'No hay datos ingresados aún'

**Diseño:**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI?node-id=65%3A209

![image](https://user-images.githubusercontent.com/72990925/102365177-06672780-3f96-11eb-8b1c-d7f15c51638d.png)

**Comment by jonathan-cembranos** [comment]
En espera debido a un bug

**Comment by jonathan-cembranos** [comment]
Este Issue tiene un bug #125

**Comment by Kathy-Damires** [comment]
bug #151
