### ISSUE TITLE
Login - Seleccionar opción de 'Ingresar'

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#5]
**Meta:** Como usuario de STB Simulador de préstamos quiero poder tener un formulario de 'Ingreso' que me permita autenticarme en la aplicación

**Alcance:** Creación de formulario y componentes del login
**Nota:** Tener en cuenta que habrán dos tipos de usuario:                                                                                  
- Funcionario STB
- Usuario regular

**Dado** un usuario no autenticado en el sitio web
**Cuando** el usuario selecciona el botón de 'Ingresar' en la página principal
**Entonces** es redirigido a el login
y el título es 'Ingreso'
y existen los campos con título 'Email *' y 'Contraseña *' ambos de tipo textbox
y hay dos botones 'Ingresar' y 'Registrarse'
y el botón de 'Registrarse' está siempre habilitado
y el botón de 'Ingresar' se habilita únicamente cuando ambos campos  'Email *' y 'Contraseña *' no están vacíos

**Escenario 1 - Formato email incorrecto**
**Dado** un usuario no autenticado en el sitio web
**Cuando** el usuario no ingresa un email válido
**Entonces** se muestra una validación debajo del campo 'Email' en color rojo y el texto de la misma es 'El formato del email ingresado no es correcto, por favor verifique'

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI?node-id=65%3A209
![image](https://user-images.githubusercontent.com/72990925/97317739-e2b31b00-1849-11eb-8026-326a76146ce2.png)

**Comment by jonathan-cembranos** [comment]
Issues ok.
