### ISSUE TITLE
FE - Guardar información de préstamo

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#50]
Cuando se ingresa la información del préstamo y se solicita el mismo guardar la solicitud y la información asociada.

**Comment by jonathan-cembranos** [comment]
Issue no terminada.
Los datos del prestamo no se guardan en la base de datos.

**Comment by RominaGlobant** [comment]
Preguntas:

1.  El boton que se visualizará para poder guardar el prestamo, qué dirá? "Guardar préstamo", ó "Guardar información de préstamo" o "Guardar" ? Qué color tendrá? No encontré la información en el figma.
2.  En qué parte de la UI se visualizará dicho botón? No encontré la información en el figma.
3.  Una vez guardado el resultado del prestamo solicitado, qué sucede? Ejemplo: se muestra un mensaje que diga: "Información de prestamo guardada"
4. La información del prestamo solicitado se guarda en la DB?
5. Habrá una sección para consultar la información guardada de los préstamos? (Para el usuario)

**Comment by jonathan-cembranos** [comment]
Los datos del préstamo se guardan en una base de datas hosteada en atlas y los únicos usuarios que pueden consultar esta información son aquellos que tengan el rol de administrador

**Comment by RominaGlobant** [comment]
Respuestas:

1. El boton que se visualizará para poder guardar el prestamo, qué dirá? "Guardar préstamo", ó "Guardar información de préstamo" o "Guardar" ? Qué color tendrá? No encontré la información en el figma. El botón de " Solicitar Préstamo" es el que guarda en la base de datos la información del prestamo.
2. En qué parte de la UI se visualizará dicho botón? No encontré la información en el figma. N/A
3. Una vez guardado el resultado del prestamo solicitado, qué sucede? Ejemplo: se muestra un mensaje que diga: "Información de prestamo guardada". Cuando se le da click al boton "Solicitar Prestamo" automaticamente eso es lo que hace
4. La información del prestamo solicitado se guarda en la DB? Sí, en la base de datos hosteada en Atlas.
5. Habrá una sección para consultar la información guardada de los préstamos? (Para el usuario) Sí.
