### ISSUE TITLE
[Login - Validaciones] Validación de autenticación de usuario regular exitosa

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#54]
**Precondiciones:**
Se debe contar con las credenciales válidas de un usuario regular

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1: Ingresar al Simulador de Préstamos | 
2: Cliquear el botón 'ingresar'| 
3: Ingresar correo y contraseña válidos de un usuario regular y cliquear 'Ingresar'| El usuario es redirigido al formulario de simulación

=======================================================

**US asociada:**
#6

**Comment by jonathan-cembranos** [comment]
Probado.
