### ISSUE TITLE
[Login - Validaciones] Validación de autenticación de usuario funcionario exitosa

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#55]
**Precondiciones:**
Se debe contar con las credenciales válidas de un usuario funcionario

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1: Ingresar al Simulador de Préstamos | 
2: Cliquear el botón 'ingresar'| 
3: Ingresar correo y contraseña válidos de un usuario funcionario y cliquear 'Ingresar'| El usuario es redirigido a la página de visualización de préstamos

=======================================================

**US asociada:**
#6

**Comment by jonathan-cembranos** [comment]
Probado.
La tabla está incompleta (en progreso).
