### ISSUE TITLE
[Login - Botón Ingresar] Validar que cuando el usuario está deslogueado se visualiza el botón 'Ingresar' 

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#56]
**Precondiciones:**
El usuario debe estar deslogueado

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Ingresar al simulador de préstamos con usuario deslogueado| 
2: Visualizar la página principal| En el extremo superior derecho se visualiza el botón 'Ingresar' acorde a los wireframes

=======================================================

**US asociada:**
#7

**Comment by jonathan-cembranos** [comment]
issue ok.
