### ISSUE TITLE
Login - Validaciones

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#6]
**Meta:** Como usuario de STB Simulador de préstamos quiero que el formulario me muestre validaciones de manera que la información que se ingresa de autenticación sea la correcta y esté informado de lo que sucede

**Alcance:** Validaciones de:
- Combinación de Email y Contraseña
- Éxito en la autenticación

**Nota:** No se bloquearán usuarios por intentos incorrectos de login

**Escenario 1 - Combinación de Email y Contraseña incorrecta**
**Dado** un usuario no autenticado en el sitio web
**Cuando** el usuario ingresa una combinación de email-contraseña no existente y selecciona el botón 'Ingresar'
**Entonces** se muestra una validación debajo del campo 'Contraseña' en color rojo y el texto de la misma es 'Los datos ingresados no son correctos, por favor verifique'

**Escenario 2 - Éxito en la autenticación**
**Dado** un usuario no autenticado en el sitio web
**Cuando** el usuario ingresa una combinación de email-contraseña válida
**Entonces** si el usuario es de tipo regular este es redirigido al formulario de simulación y si el usuario es de tipo funcionario el mismo es redirigido a la página de visualización de préstamos

**Nota:** De momento al  no existir las páginas mencionadas en el escenario 2 es válido redirigir al usuario a una blank page siempre que según el tipo de usuario las páginas sean diferentes.

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI?node-id=65%3A209

**Comment by Andrew-MartinezH** [comment]
Tengo un inconveniente que es que el error se muestra solo despues del segundo click

**Comment by jonathan-cembranos** [comment]
Issue no terminado

**Comment by jonathan-cembranos** [comment]
issue ok.
Funciona bien pero existe un bug reportado con respecto al mensaje de error en el login, issue #69
