### ISSUE TITLE
Implementar correcciones del ticket 44 de UI

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#60]
- Logo con redireccion a home.
- Arreglar linea del header (que esté al 100% en ancho).
- Modificar estilos de todos los titulos.
- Modificar el alto de los input a un 32px (en figma está en 40px).
- Checkbox en color naranja en Simulador de prestamos.
- Alineacion de ckeckbox en Simulador de prestamos.
- Correjir alto en botones basandose en figma.
- Ajustar padding entre label e input (basandose en figma)
- En Resultado de prestamo modifcar fuente en general.

**Comment by RominaGlobant** [comment]
El test case #76 fue asociado por error a esta US #60

**Comment by RominaGlobant** [comment]
Preguntas en función de las correcciones realizadas:

1. _Alineacion de ckeckbox en Simulador de prestamos:_ ¿Qué alineación tenía y qué alineación debe tiene ahora? El figma está actualizado?
2. _Corregir alto en botones (en general, diferenciar entre primario 168 x 40 px y secundario 168 x 40 px):_ ¿Están bien estas medidas? En caso de que no, ¿Cuáles son las esperadas?
3. _En Resultado de prestamo modifcar fuente en general:_  ¿Cuáles fueron los cambios? #81 
4. En la sección que visualizamos la devolución del préstamo, según figma veo que dice: "Resultado del préstamos", ¿Está ok? Vimos con Marce que debería de decir: "Resultado del préstamo" ó "Resultado de los préstamos".
Ejemplo: 

![image](https://user-images.githubusercontent.com/73701083/104059933-e31a4b80-51d4-11eb-87fb-819a19cd6ae0.png)


Si bien varias dudas fueron evacuadas el Jueves 07/Jan, me quedaron estas pendientes.

Muchas gracias!

**Comment by jonathan-cembranos** [comment]
Issue ok.
