### ISSUE TITLE
Dropdowns y botones tabla 'Solicitud de préstamos'

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#67]
**Meta:** Como usuario de STB Simulador de préstamos quiero que el botón de 'Limpiar' borre las lineas seleccionadas y únicamente aparezcan con dropdown aquellos préstamos que se encuentren en estado 'Pendiente' y al seleccionar los mismos aparezcan las opciones 'Aprobar' y 'Rechazar'

**Escenario 1 - Dropdown en préstamos 'Pendiente'**
**Dado** un usuario admin en la página de visualización de solicitudes de préstamos
**Cuando** el usuario selecciona un préstamo el cual se encuentra en estado 'Pendiente'
**Entonces** visualiza un dropdown con las opciones 'Aprobar' y 'Rechazar'
y al realizar un cambio automáticamente la línea se selecciona ( fondo naranja claro)
y el botón de 'Limpiar' se habilita (debe estar deshabilitado por defecto si no hay ninguna linea seleccionada'

**Escenario 2 - Préstamos en estado final**
**Dado** un usuario admin 
**Cuando** el usuario se encuentra en la página de visualización de solicitudes de préstamos
**Entonces** no se muestran dropdowns para aquellos préstamos los cuales se encuentran en estado 'Aprobado' o 'Rechazado'

**Escenario 3 - Selección del botón 'Limpiar**
**Dado** un usuario admin el cual se encuentra en la página de visualización de solicitudes de préstamos y ha realizado cambios de estados en préstamos pendientes de aprobación sin haber aplicado los cambios 
**Cuando** el usuario selecciona el botón de 'Limpiar'
**Entonces** aquellos préstamos a los cuales se les había cambiado el estado sin confirmarlo vuelven a estar como 'Pendientes'
y ya no se encuentran seleccionados con fondo
y el botón de 'Limpiar' se deshabilita

**Escenario 4 - Borrar columna checkbox**
Borrar la columna checkbox

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI?node-id=65%3A209

**Comment by NachoGlobant** [comment]
@evadathaguyGlobant, no entendí el escenario 4. Se debe borrar esa columna?

Gracias!

**Comment by evadathaguyGlobant** [comment]
Hola @NachoGlobant, sí porque no tiene mucho sentido tener esa columna, para hacer el cambio in bulk digamos no es necesaria

**Comment by NachoGlobant** [comment]
> Hola @NachoGlobant, sí porque no tiene mucho sentido tener esa columna, para hacer el cambio in bulk digamos no es necesaria

Gracias, Eva!
