### ISSUE TITLE
[Boton Ingresar/Login] El error se muestra solo cuando se da un segundo click en el boton 'Ingresar'

### ISSUE THREAD

**Issue by Andrew-MartinezH** [GlobantUy/STB-Bank#69]
**Reproducción**
Pasos para reproducir el bug:
1. Ir a la pagina 'Ingreso'
2. Ingresar un usuario no registrado en la base de datos
3. Cliquear el boton 'Ingresar' 

**Resultado Esperado**
Un mensaje de error diciendo que los datos ingresados son incorrectos luego de hacer click.

**Resultado Obtenido**
El mensaje de error se muestra luego de realizar un segundo click.

**Capturas**

https://user-images.githubusercontent.com/72889964/103678887-e3131500-4f62-11eb-9afd-88630aea0f94.mp4

**Datos del dispositivo:**
 - Sistema operativo: Windows
 - Browser: chrome

**Comment by jonathan-cembranos** [comment]
Y al darle otro clic una vez muestre el error el mismo desaparece.

**Comment by jonathan-cembranos** [comment]
Issue ok.
