### ISSUE TITLE
Login - Botón Ingresar

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#7]
**Meta:** Como usuario que accede a la web de STB Simulador de préstamos quiero tener un botón en la página principal que me permita acceder al formulario de 'Ingresar' para poder autenticarme en la aplicación.

**Alcance:** Creación del botón de 'Ingresar' en la página principal

**Escenario 1 - Visualización del botón**
**Dado** un usuario no autenticado en el sitio web
**Cuando** el usuario accede a la página principal
**Entonces** a la derecha arriba puede encontrar un botón con el texto'Ingresar' el cual estará habilitado siempre que el usuario no se encuentre logueado en la aplicación
y se ha aplicado correctamente el diseño de los wireframes

**Escenario 2 - Selección del botón 'Ingresar**
**Dado** un usuario no autenticado en el sitio web
**Cuando** el usuario selecciona el botón de 'Ingresar'
**Entonces** se redirige al usuario a un nuevo formulario detallado en el ticket https://github.com/GlobantUy/STB-Bank/issues/5

**Diseño**
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI?node-id=65%3A209

**Comment by jonathan-cembranos** [comment]
Issues ok.
