### ISSUE TITLE
Creacion del endpoint para registrar usuarios (BE)

### ISSUE THREAD

**Issue by Kevin-Mora-Pais** [GlobantUy/STB-Bank#70]

**Comment by RominaGlobant** [comment]
Preguntas:

1. Cuál es el endpoint para registrar usuarios?
2. En 1 request el endpoint permite registrar varios usuarios a la vez? (Ejemplo, pasándole una lista de 5 usuarios a crear, me los crea o tiene que ser de a 1 usuario a la vez?)
3. Cuál es el resultado esperado una vez registrado el o los usuarios? (Status code, response, etc)
4. En caso de fallar el endpoint, qué errores maneja? (Ej: 403 permisos, 500, etc) 

Muchas gracias!

**Comment by jonathan-cembranos** [comment]
issue ok.
