### ISSUE TITLE
[BE - Endpoint para registrar usuarios] POST Registrar usuarios

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#76]
Endpoint info:

HTTP method: POST
Request: https://backendmain-pdz54353z.vercel.app/api/register
Body:
{
    "name": "NameofUser",
    "lName": "SurnameofUser",
    "dateOfBirth": "12/1/1980",
    "gender": "Male",
    "preferences": ["Comida", "Opticas"],
    "email": "devTest2@test.com",
    "department": "Montevideo",
    "passwd": "passwd"
}
Expected result: Status code "200" and json response with "OK"

Notes: 
- El manejo de errores está implementado, no visualizamos el status code pero sí en formato mensaje que indicará qué falla y el motivo
- En el caso de estar utilizando Postman y en la response obtener algo similar a "NO_RESPONSE_FROM_FUNCTION" notificar al Dev.

**US asociada:**
_[https://github.com/GlobantUy/STB-Bank/issues/70]_

**Comment by jonathan-cembranos** [comment]
issue ok.
