### ISSUE TITLE
[Logo con redirección a home] Validar que el logo de STB Bank redireccione al home

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#77]
**Precondiciones:**
_[Estar logueado en STB y estar en otra sección que no sea el home]_

=======================================================

Scenario 1) desde la sección "Solicitudes" validar el redreccionamiento del STB logo

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Loguearse con privilegios de funcionario para poder visualizar la sección de "Solicitudes" | 
2: Visualizar la sección de "Solicitudes"| 
3: Una vez en la sección de "Solicitudes", hacer click en el logo de STB | El logo de STB debe redirigirnos al Home

Scenario 2) desde la sección "Resultado de préstamos" validar el redirecionamiento del STB logo

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1: Ingresar todos los datos requeridos para simular un prestamo | 
2: Click en "Simular préstamo" | Visualizar la sección de "Resultado del préstamos" con la información correspondiente
3: Una vez en la sección de "Resultado del préstamos", hacer click en el logo de STB | El logo de STB debe redirigirnos al Home

Scenario 3) desde la sección "Registro" validar el redirecionamiento del STB logo

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1: Estar en la sección de "Registro" de usuario | 
2: Una vez en la sección de "Registro" hacer click en el logo de STB | El logo de STB debe redirigirnos al Home

Notes: a medida que se vayan agregando mas paginas/sessiones se deberá validar el redireccionamiento del STB logo

=======================================================

**US asociada:**
_[https://github.com/GlobantUy/STB-Bank/issues/60]_

**Comment by jonathan-cembranos** [comment]
issue ok.
