### ISSUE TITLE
[UI/Estilo de los títulos] Validar los estilos de todos los títulos.

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#78]
Objetivo: validar que todos los titulos existentes tengan las mismas caracteristicas entre si y siguiendo los stándares presentes en figma

Títulos:

- Simulador de préstamo
- Solicitudes
- Resultado del préstamos
- Ingreso
- Registro

Figma: https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

Resultado esperado:

/* TITULO */

font-family: Roboto;
**font-style: normal;**
font-weight: normal;
font-size: 24px;
line-height: 28px;

**US asociada:**
_[https://github.com/GlobantUy/STB-Bank/issues/60]_

**Comment by jonathan-cembranos** [comment]
A simple vista los títulos se ven como en el figma sin embargo existen algunos detalles a revisar:

1. Los títulos : “Simulador de préstamos”, “Resultado de préstamo” y “Ingreso” no tienen (o no es lo especificado en el figma) la propiedad “line-height: 28px;”

2. “Simulador de préstamos”, “Solicitudes de préstamo”, “Resultado de préstamo” y “Ingreso” existe una modificación en la propiedad “font-family” además de tener el atributo “Roboto” tienen “sans-serif” en resumen los títulos mencionados tienen “font-family: 'Roboto', sans-serif;”

**Comment by jonathan-cembranos** [comment]
“Solicitudes de préstamo” y “Resultado de préstamo” son h2

**Comment by jonathan-cembranos** [comment]
en espera

**Comment by jonathan-cembranos** [comment]
issue ok.
