### ISSUE TITLE
[UI/Altura de los Input] Validar que el alto de los input sea de 32px.

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#79]
Objetivo: validar que el alto de los input sea de 32px.

Inputs:

- Ingreso
- Monto a pedir
- Email
- Contraseña
- Nombres
- Apellidos
- Confirmación de contraseña

En figma aparecen de 28px
Figma: https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

Resultado esperado:

/* Input */

position: absolute;
width: 55px;
**height: 32px;**
left: 120px;
top: 1229px;

US asociada:
[https://github.com//issues/60]

**Comment by jonathan-cembranos** [comment]
issue ok.

**Comment by jonathan-cembranos** [comment]
Se decidió modificar algunos estilos tras consultarlo entre todos.
