### ISSUE TITLE
FE - Elementos de pantalla de simulador de préstamo

### ISSUE THREAD

**Issue by evadathaguyGlobant** [GlobantUy/STB-Bank#8]
**Meta:** Como usuario que accede a la web de STB Simulador de préstamos quiero tener implementada la UI del simulador de préstamos

**Alcance:** Creación de los elementos de la pantalla de simulación de préstamo, de momento los mismos no triggerean ninguna acción ni validaciones, lo ultimo será parte de otra historia

**Elementos de la pantalla:**
Título - 'Simulador de préstamos'
'Ingreso' - textbox de tipo numérico
'Monto a pedir'- textbox de tipo numérico
'Moneda del préstamo' - radio button, solo un valor a la vez ('U$S', '$U')
'Años de financiación' - dropdown - fijos - 10, 15, 20, 25, 30
'Tipo de préstamo' - checkbox - Inmueble, Automotor, Otros
'Simular préstamo' - botón, deshabilitado por defecto

![image](https://user-images.githubusercontent.com/72990925/98133644-99dc1180-1e9c-11eb-938b-86c00398e754.png)

Diseño
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**Comment by jonathan-cembranos** [comment]
Issues ok.
Se muestran todos los elementos mencionados. 

-Aunque el último checkbox  ('Tipo de préstamo' - checkbox - Otros) tiene un error de alineación (ya marcado como un bug).
