### ISSUE TITLE
[UI/Resultado de préstamo - fuente] Validar tipografía

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#81]
Objetivo: Validar que en la sección de "Resultado de préstamo" todos los tipos de fuentes hayan sido modificados según previas reuniones con diseño.

Figma: https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI (pendiente de actualizar con el type font correcto)

Resultado esperado: el tipo de fuente debe ser {tipo de fuente = Roboto ó Heebo? }

US asociada:
[https://github.com//issues/60]

**Comment by jonathan-cembranos** [comment]
Todos los tipos de fuente concuerdan con el figma, excepto por el botón “volver a simular” (Bug por reportar)

**Comment by jonathan-cembranos** [comment]
Issue ok.
Bug areglado.
