### ISSUE TITLE
[UI/padding entre label e input] Validar el ajuste del padding entre label e input

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#82]
Objetivo: validar para todas las secciónes que el padding entre label e input tenga el ajuste que figura en figma.

Figma: https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

Resultado esperado: ajuste 4dp

Ejemplo: 
![image](https://user-images.githubusercontent.com/73701083/104054177-5e76ff80-51cb-11eb-81ab-42e365887b84.png)

US asociada:
[https://github.com//issues/60]

**Comment by jonathan-cembranos** [comment]
Issue ok.
Entre los label e input hay 4px (en todas las páginas).
