### ISSUE TITLE
[UI/Headers] Validar el ancho de los headers

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#83]
Objetivo: validar para todas las secciones el ancho del header.

Figma: https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

Resultado esperado: ancho 100%

Ejemplo header:

![image](https://user-images.githubusercontent.com/73701083/104057991-ca5c6680-51d1-11eb-991d-315a7c76a042.png)

US asociada:
[https://github.com//issues/60]

**Comment by jonathan-cembranos** [comment]
issue ok.
