### ISSUE TITLE
[Guardar prestamo/Backend] No se almacena el tipo de prestamo.

### ISSUE THREAD

**Issue by Kevin-Mora-Pais** [GlobantUy/STB-Bank#85]
**Reproducción**
Pasos para reproducir el bug:
1. Popular con informacion la pagina "Solicitar prestamo"
2. Hacer click en "Simular prestamo" (de momento es el boton que acciona el POST).

**Resultado Esperado**
La totalidad de los datos ingresados a la pagina se almacenan en la base de datos.

**Resultado Obtenido**
No se guarda el campo "Tipo de prestamo"

**Datos del dispositivo:**
 - Windows 10
 - Postman

**Comment by jonathan-cembranos** [comment]
No se envia en el post
