### ISSUE TITLE
[Guardar prestamo/Backend] El atributo "userName" recibe el valor del email del usuario.

### ISSUE THREAD

**Issue by Kevin-Mora-Pais** [GlobantUy/STB-Bank#87]
**Resultado Esperado**
El atributo "userName" recibe el nombre del usuario en base a su email.

**Resultado Obtenido**
Se le asigna el valor del email.

**Datos del dispositivo:**
 - Windows 10
 - Postman

**Comment by jonathan-cembranos** [comment]
issue ok.
