### ISSUE TITLE
[UI/Visualización de préstamos] Validar la sección de préstamos solicitados cuando no hay préstamos

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#88]
**Precondiciones:**
_[Estar logueado en STB bajo el rol de Admin (utilizando las credenciales de Admin) y que no existan préstamos para listar.]_

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1: Una vez logueado como Admin, navegar hasta la página de visualización de solicitud de préstamos  | 
2: Observar | Si no hay préstamos para listar en la tabla, el dropdown de filtros se encuentra vacío, el botón de aplicar cambios no está en la página, hay una imágen y el texto "No hay datos ingresados aún".

Figma:
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI?node-id=65%3A209

Imagen:
![image](https://user-images.githubusercontent.com/73701083/104489036-f4d16980-55ad-11eb-868e-5e6a1b4bdda4.png)

=======================================================

**US asociada:**
_[https://github.com/GlobantUy/STB-Bank/issues/48]_

**Comment by jonathan-cembranos** [comment]
Este Issue no está terminado debido a un bug #125

**Comment by jonathan-cembranos** [comment]
Ese bug aún está activo y sin resolver.

**Comment by jonathan-cembranos** [comment]
issue ok.
