### ISSUE TITLE
[UI/Página de visualización de préstamos] Validación de los elementos creados - Título de la página

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#90]
**Precondiciones:**
_[Estar logueado en STB bajo el rol de Admin (utilizando las credenciales asignadas para el Admin) y poder visualizar la página de visualización de préstamos para poder validar los elementos presentes.]_

=======================================================

Elemento a visualizar | Resultado Esperado
------------ | -------------
1: Título | El titulo a visualizar debe de ser 'Solicitudes de préstamo' y las propiedades son: {actualizar figma}

=======================================================

Figma:
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

**US asociada:**
_[Link a la US asociada #45 ]_

**Comment by jonathan-cembranos** [comment]
En espera debido a un bug

**Comment by jonathan-cembranos** [comment]
En el figma el título es  “Solicitudes” en cambio en la app y está Test Case aparece como “Solicitudes de préstamo”. ¿Cuál de estas dos es la correcta?

**Comment by RominaGlobant** [comment]
@jonathan-cembranos “Solicitudes de préstamo” es la correcta. Gracias
