### ISSUE TITLE
[UI/Página de visualización de préstamos] Validación de los elementos creados - Tabla con campos

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#92]
Precondiciones:
[Estar logueado en STB bajo el rol de Admin (utilizando las credenciales asignadas para el Admin) y poder visualizar la página de visualización de préstamos para poder validar los elementos presentes.]

=======================================================

Elementos a visualizar | Resultado Esperado
------------ | -------------
1: Tabla con 7 campos | 
1.1: Columna con formato checkbox a partir de la segunda linea | 
1.2: Colmuna con el título 'Usuario' | Visualizar el nombre del usuario que solicitó el préstamo
1.3: Colmuna con el título 'Moneda' | Visualizar la moneda en la que se solicitó el préstamo
1.4: Colmuna con el título 'Monto solicitado' | Visualizar el monto del préstamo
1.5: Colmuna con el título 'Cuotas' | Vusualizar la cantidad de cuotas en las que se solicitó financiar el préstamo
1.6: Colmuna con el título 'Fecha' | Visualizar la fecha en la que se solicitó el prestamo, formato: día (10) Mes (Jul - texto) año (2020)
1.7 Colmuna con el título 'Estado' | Visualizar el estado del préstamo: Aprobado | Pendiente | Rechazado

Se deberán de contemplar las propiedades especificadas en figma {actualizar}

![image](https://user-images.githubusercontent.com/73701083/104496054-39adce00-55b7-11eb-82df-aa56df6cfa8d.png)

=======================================================

Figma:
https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI

US asociada:
[Link a la US asociada #45 ]

**Comment by Kathy-Damires** [comment]
En la tabla realizada se decidió sacar la columna que contiene los checkbox. El resto de los elementos se encuentran creados, la única diferencia es que la fecha se encuentra en formato numérico separado con guiones medios, el cuál es diferente al especificado:
![image](https://user-images.githubusercontent.com/56728912/106802876-4e273880-6642-11eb-9f0f-fcef06ed2ccf.png)

**Comment by RominaGlobant** [comment]
@SebastianPi2020  podrías confirmar que el formato de la fecha si bien difiere con el de figma sea el esperado según las validaciones de @Kathy-Damires ?

Muchas gracias

cc @NachoGlobant

**Comment by SebastianPi2020** [comment]
Hable con Eva sobre el asunto de la fecha ya que difiere con el del figma y me dijo que era valido dejarlo de esa forma, igual si se requiere un cambio sobre ese asunto podría hacerlo.
