### ISSUE TITLE
[UI/Página de visualización de préstamos] Validación de los elementos creados - Botón 'Aplicar cambios'

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#93]
Precondiciones:

[Estar logueado en STB bajo el rol de Admin (utilizando las credenciales asignadas para el Admin) y poder visualizar la página de visualización de préstamos para poder validar los elementos presentes.]

=======================================================

Elemento a visualizar | Resultado Esperado
------------ | -------------
Scenario 1
1: Botón 'Aplicar cambios' | Una vez que el Admin visualiza la tabla con campos #92 también deberá de visualizar el botón 'Aplicar cambios' el cual estará deshabilitado por defecto (color gris) si no se seleccionó ningúno de los checkbox presentes.

![image](https://user-images.githubusercontent.com/73701083/104498087-00c32880-55ba-11eb-8b11-97ca4413268d.png)

Elemento a visualizar | Resultado Esperado
------------ | -------------
Scenario 2
2: Botón 'Aplicar cambios' | Una vez que el Admin visualiza la tabla con campos #92 y selecciona uno de los checkbox, el botón 'Aplicar cambios' deberá lucir como activo (color anaranjado intenso).

![image](https://user-images.githubusercontent.com/73701083/104498141-0d478100-55ba-11eb-912e-8ef18c10dd15.png)

Elemento a visualizar | Resultado Esperado
------------ | -------------
Scenario 3
3: Botón 'Aplicar cambios' | Una vez que el Admin selecciona uno de los checkbox y el botón 'Aplicar cambios' luce como activo (color anaranjado intenso) y los cambios se aplican, el botón queda inhabilitado nuevamente por defecto y los checkboxs no lucen marcados.

![image](https://user-images.githubusercontent.com/73701083/104498289-42ec6a00-55ba-11eb-813d-248cab67596c.png)

Las propiedades del botón 'Aplicar cambios' deben coincidir con la información presente en figma {actualizar}

Figma: https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI
=======================================================

**US asociada:**
_[Link a la US asociada #45 ]_

**Comment by Kathy-Damires** [comment]
En este caso, al haber removido los checkboxs, el botón se habilita al cambiar el estado en el dropdown de la tabla a aprobado o rechazado. Vuelve a estado deshabilitado al limpiar los cambios o cambiar al dropdown a pendiente.

**Comment by RominaGlobant** [comment]
@SebastianPi2020 podrías confirmarnos que las observaciones de @Kathy-Damires son las esperadas incluso cuando los checkbox fueron removidos?

1. El boton 'Aplicar Cambios' se **habilita** cuando se cambia el estado del prestamo de Pendiente a Aprobado
2. El boton 'Aplicar Cambios' se **habilita** cuando se cambia el estado del prestamo a Pendiente a Rechazado
3. El boton 'Aplicar Cambios' se **deshabilita** cuando se limpian los cambios
4. El boton 'Aplicar Cambios' se **deshabilita** cuando el estado es Pendiente

Preguntas: 
Qué pasa si se cambia el estado del prestamo de Rechazado a Aprobado?
Qué pasa si se cambia el estado del prestamo de Aprobado a Rechazado?

Muchas gracias

cc @NachoGlobant

**Comment by SebastianPi2020** [comment]
Hola buenas, cada vez que que se cambia el estado del préstamo de Pendiente a Rechazado o Aprobado se habilita el botón aplicar cambios y también el botón limpiar. También se deshabilita el botón limpiar y el de aplicar cambios cuando el estado del préstamo es solamente Pendiente. Y en el caso de que el estado del préstamo cambie entre Rechazado o Aprobado se mostraran los botones de Aplicar cambios o limpiar habilitados para poder limpiar esos cambios o sino poder aplicarlos como desee el usuario Admin.
