### ISSUE TITLE
[Confirmar prestamo/Pop up usuario logueado] Según el issue #32 escenario 1.1 al apretar el botón 'Solicitar préstamo' se muestra un pop-up muestra el valor del prestamo a pedir y la cantidad de cuotas que el usuario seleccionó

### ISSUE THREAD

**Issue by Kathy-Damires** [GlobantUy/STB-Bank#94]
**Reproducción**
Pasos para reproducir el bug:
1. Simular un prestamo
2. Ir a la pagina donde se muestran los resultados del prestamo
3. Seleccionar una fila de la tabla
4. Clickear el boton simular prestamo
5. Ver el error en el popup

**Resultado Esperado**
Mostrar un texto que muestra el monto solicitado y la cantidad de cuotas elegidas por el usuario
**Resultado Obtenido**
Muestra un texto establecido por defecto 

**Capturas**
![image](https://user-images.githubusercontent.com/56728912/104500325-0bcb8800-55bd-11eb-8f38-25bf8ddfd760.png)

![image](https://user-images.githubusercontent.com/56728912/104500449-37e70900-55bd-11eb-8605-98af83fb2e18.png)

**Datos del dispositivo:**
 - Sistema operativo: Windows
 - Browser chrome

**Comment by jonathan-cembranos** [comment]
issue ok.
