### ISSUE TITLE
[UI/Página de visualización de préstamos] Validación de los elementos creados - Botón 'Limpiar'

### ISSUE THREAD

**Issue by RominaGlobant** [GlobantUy/STB-Bank#95]
**Precondiciones:**
[Estar logueado en STB bajo el rol de Admin (utilizando las credenciales asignadas para el Admin) y poder visualizar la página de visualización de préstamos para poder validar los elementos presentes.

También el Admin deberá de tener pre-seleccionados 1 ó + checkbox y haber modificado el valor original del campo 'Estado' del préstamo]

=======================================================

Elemento a visualizar | Resultado Esperado
------------ | -------------
1:  Botón 'Limpiar' | Visualizar el botón 'Limpiar' debajo de la 'tabla con campos' ubicado del lado derecho (y a la izquierda del botón de 'Aplicar cambios'), el imsmo debe de ser un botón del tipo secundario/Enabled. 
A nivel funcional (no es parte del scope de las validaciones de UI) el comportamiento del botón lo que hace es mostrar el status original del campo 'Estado' del prestamo.

![image](https://user-images.githubusercontent.com/73701083/104501710-dc1d7f80-55be-11eb-8c24-e43f47a083e4.png)

El elemento deberá de tener las propiedades similares a las que figuran en figma {actualizar}

Figma: https://www.figma.com/file/R6G7SvqKaXCbnwta90Xdlu/ANIMA-UI
=======================================================

**US asociada:**
_[Link a la US asociada #45 ]_

**Comment by Kathy-Damires** [comment]
El botón aparece pero se encuentra a una mayor distancia de del boton "aplicar cambios" (mayor distancia que la especificada en el figma)

**Comment by RominaGlobant** [comment]
@SebastianPi2020  podrías indicarnos en base a las observaciones de @Kathy-Damires qué medidas utilizaste tú y si son las correctas?

Como ella pudo observar, el boton 'Limpiar' aparece a una mayor distancia del boton 'Aplicar cambios' según lo que está especificado en figma.

Muchas gracias

cc @NachoGlobant

**Comment by SebastianPi2020** [comment]
Pude observar el figma  y es verdad que esta diferente, por eso lo cambiare, igualmente dejare las medidas:

El botón limpiar tiene las siguientes medidas:  width: 160px; , height: 40px; left: 57%;  bottom: 10vh;
El botón aplicar cambios tienen estas medidas:  width: 160px; , height: 40px; , bottom: 10vh; , right: 15%;

**Comment by RominaGlobant** [comment]
Ok @SebastianPi2020 entonces figma esta desactualizado y las medidas son esas que compartiste las cuales @Kathy-Damires pudo visualizar en la App y las cuales no seran modificadas. ¿Es así? Gracias.

**Comment by RominaGlobant** [comment]
@SebastianPi2020 Tal como te sugirió @msantamariaglobant revisa nuevamente las medidas de los botones para hacer nuevos cambios y cuando lo tengas pronto nos compartis los datos y un print de pantalla para poder re-ejecutar el caso de prueba.
Muchas gracias! :)

cc @Kathy-Damires

**Comment by SebastianPi2020** [comment]
![Captura](https://user-images.githubusercontent.com/72942244/108246629-69a93d80-7130-11eb-8295-55dbc58473d3.PNG)

Buenas, estas son las medidas que utilice para el botón limpiar, ya que usando todas las que estaban en el figma iban a quedar en una posición completamente diferente a lo que se mostraba. 
width: 160px;
height: 40px;
left: 63%;
bottom: 10vh;
