### ISSUE TITLE
[Usuario logueado - Deslogueo] Validar que si el usuario se encuentra logueado en el Home y cliquea en su nombre, puede desloguearse

### ISSUE THREAD

**Issue by NachoGlobant** [GlobantUy/STB-Bank#97]
**Precondiciones:**
Se debe contar con un usuario válido

=======================================================

Pasos para la ejecución | Resultado Esperado
------------ | -------------
1:  Ingresar al simulador de préstamo| 
2: Estando en el Home, loguearse con un usuario válido|
3: Completar el formulario de préstamo| 
4: Desde el Home, cliquear el nombre del usuario arriba a la derecha | Se despliega la opción "Salir"
5: Cliquear afuera de la sección| El mensaje "Salir" se cierra y el usuario permanece logueado
6: Cliquear nuevamente el nombre del usuario| 
7: Cliquear "Salir"| El usuario se desloguea exitosamente, se visualiza el botón "Ingresar" y el formulario de solicitud se encuentra vacío

=======================================================

**US asociada:**
#43

**Comment by jonathan-cembranos** [comment]
issue ok.
